### PR TITLE
Some dependency updates

### PR DESCRIPTION
**Pull request by rtiangha**
The [MoltenVK](https://github.com/KhronosGroup/MoltenVK/releases) updates may improve things with Vulkan on MacOS, but testing needed.

### CODE REVIEW

**Comment by rtiangha** [comment]
Yeah, that QT download server has been having issues since yesterday; doesn't just affect things here. Re-running the jobs will eventually work.

**Comment by OpenSauce04** [comment]
Wow that Qt download server is still having issues

**Comment by rtiangha** [comment]
Yeah, it was part of the reason why I looked into updating aqtinstall; I had hoped it had better mirrors or did a better job with the timeouts or something but it looks like it didn't.

Then again, while waiting, another aqtinstall update just came out, so who knows, lol.

**Comment by BlurrySquire** [comment]
Looks like the QT servers are back up again?

**Comment by OpenSauce04** [comment]
They are, I'm just waiting on someone I've asked to check this over who has appropriate hardware

**Comment by OpenSauce04** [comment]
I have received verification that this pull request is working fine on ARM MacOS

**Review by OpenSauce04 — APPROVED** [review]

**Pull request merged**
