### PR TITLE
Android overlay: possibility to adjust the scale of individual buttons

### PR DESCRIPTION
**Pull request by gperrio**
It is still possible to change the global scale of the overlay and there is an option to reset the scale of all the elements.

### CODE REVIEW

**Review by OpenSauce04 — APPROVED** [review]
LGTM. If I had to nitpick one thing, it would be nice if the scaling happened from the center rather than the top left corner, but it's not that big of a deal

**Comment by gperrio** [comment]
There were problems with the merge, I fixed it.

**Comment by ayrudev** [comment]
ty gperrio

**Review by ayrudev — APPROVED** [review]
LGTM, although i have the same consideration as @OpenSauce04, that it should be from the center, other than that, everything's good

**Pull request merged**
