### PR TITLE
Added msvc vs msys2 explanation

### PR DESCRIPTION
**Pull request by privateemu**
**Is there an existing issue for this?**
> * [x]  I have searched the existing issues

**What feature are you suggesting?**
Adding some text to the ReadMe to clarify the difference between the two Windows versions.

**Why would this feature be useful?**
I got confused as to the differences, and I see on the Discord the question asked 33 times so far, and I am sure there are others who had the same questions and went to Discord/googled to find out. This should reduce confusion for Windows users as to which to download.

### CODE REVIEW

**Review by BlurrySquire — CHANGES_REQUESTED** [review]
Please could you add onto the bit of msvc not working sometimes. Msvc requires the visual c++ runtime to be installed which can require your computer to restart to complete the installation. If you still have issues with msvc with the runtime installed then you should try msys2.

Could you also mention that msvc is created by Microsoft and is closed source whereas msys2 is open source.

**Comment by BlurrySquire** [comment]
Sorry about all the edits I'm currently out and my phone's autocorrect is a bit weird.

**Comment by privateemu** [comment]
@BlurrySquire Added a bit more clarity, thanks for mentioning those! Did not find those details on my search of answers on Discord

**Comment by privateemu** [comment]
Based on all the above, might it be safe to recommend that the MSYS2 version over the MSVC unless one is more concerned about the file size download? It feels like the MSYS2 version the benefits of more stability, open-source, not requiring another install, the only downside being 20 MB larger (which is admittedly 50%) .

**Comment by BlurrySquire** [comment]
I'm not sure. Your points are definitely valid. I'll put this forward in the organisation chat on discord.

**Review by BlurrySquire — APPROVED** [review]
Everything looks good to me. The explanation of the differences is quite simple. This is good because people who aren't developers will be using the emulator.

**Comment by ghost** [comment]
I feel like this won't be relevant once the Windows Installer is done, since we're probably gonna pick  only one of these for the installer

**Comment by BlurrySquire** [comment]
> I feel like this won't be relevant once the Windows Installer is done, since we're probably gonna pick only one of these for the installer

It probably won't but we won't have the installer ready anytime soon, so I think we should merge it for the time being. Also, it will be useful for those that don't want to use the installer for some reason.

**Comment by OpenSauce04** [comment]
> I feel like this won't be relevant once the Windows Installer is done, since we're probably gonna pick only one of these for the installer

There will be installers for both

> It probably won't but we won't have the installer ready anytime soon

The installer is in the roadmap for the very next release

**Comment by ghost** [comment]
> There will be installers for both

I think Citra never had both either? I guess if we're going that route than yeah its good

**Comment by BlurrySquire** [comment]
> > There will be installers for both
> 
> I think Citra never had both either? I guess if we're going that route than yeah its good
> 
> 

Citra downloaded from the web, our installers come with Lime3DS bundled in the installer so I see no point in just not making an installer for the other windows build.

**Comment by BlurrySquire** [comment]
> > > There will be installers for both
> > 
> > I think Citra never had both either? I guess if we're going that route than yeah its good
> > 
> > 
> 
> Citra downloaded from the web, our installers come with Lime3DS bundled in the installer so I see no point in just not making an installer for the other windows build.

**Comment by ghost** [comment]
Ok i see

**Pull request merged**
