### PR TITLE
Begin rebranding UI. Replacing 'citra' with 'lime'.

### PR DESCRIPTION
**Pull request by BlurrySquire**
I have started to rebrand some of the UI in citra. I have replaced the name 'citra' with 'lime'. I also started replacing the citra icons with the lime icons. Please note: I was unable to get a working build as I could not resolve the Qt6 error I was getting.

### CODE REVIEW

**Comment by ryzendew** [comment]
i hope this one builds fully

**Comment by ryzendew** [comment]
Windows builds failed

**Comment by BlurrySquire** [comment]
This is quite annoying. It is sad we don't have any of the past citra devs able to help us. We are going to have to find developers that know what they are doing, because I don't either. I've never used cmake but I have used make.

**Comment by ryzendew** [comment]
take all the time you need

**Comment by BlurrySquire** [comment]
I think we need to get the Qt6 SDK and tell CMake where it is.

**Comment by ayrudev** [comment]
ok.. im trying to fix the build problems so it builds without any errors, then i might pull, trying to figure this out

**Comment by BlurrySquire** [comment]
Alright, Good luck. I really hope we can get Citra back to a point where people can start adding new things.

**Pull request closed without merging**
