### PR TITLE
Update various submodules

### PR DESCRIPTION
**Pull request by rtiangha**
Ever since the shutdown, I've been playing around seeing how far I could get in updating the various third-party modules since many of them hadn't been touched in a while. Here are the results of that work without having to modify `.gitmodules`; feel free to cherry-pick the ones that would work best or merge them all.

On my personal repositories, I also have `ext-boost` updated from 1.82.0 to 1.84.0 (and 1.85.0.beta1 on a different branch) and `ext-libressl-portable` from 3.8.0 to 3.9.1. I think the Lime3DS project should have its own mirrors of those repositories (you can fork mine if you want the latest stuff) because the old citra-emu account hosted their own copies of those repositories as well.

### CODE REVIEW

**Comment by BlurrySquire** [comment]
We're gonna have a lot of repos to make then, even if it is just forking them. Were the repos containing third-party libraries private or public? Also thank you for updating the stuff, I didn't even think about the possibility of updating them.

**Comment by rtiangha** [comment]
Well, as an example, the Citra project had their own versions of Boost and libressl because they modified their build scripts to slim things down a bit. Boost, for instance, is a huge library and having to clone the entire repository every time there was a build request took a lot of time and disk space. So for Boost, they just copied over only the header and source files they used and served those up to the build bots rather than the entire stock project. As for libressl, they skipped building the installer, test suite, etc, which saved time in compiling, but they had to modify the build scripts in order to do so. That implied that someone had to manually update the repositories whenever upstream had a new release though, so that meant there was a maintenance burden because of it. 

You can get an idea of the sorts of repositories the old project hosted themselves via the Wayback Machine:

https://web.archive.org/web/20240304193810/https://github.com/orgs/citra-emu/repositories

Usually, the ones prefaced with `ext-` were custom ones that they modified from the main project repositories. `ext-soundtouch` isn't needed anymore though, since somewhere along the line, someone chose to go with the stock project repository instead, which makes maintenance easier.

**Comment by BlurrySquire** [comment]
Ok, I think we would benefit from switching over to self maintained repos. It would decrease build time and allow for custom modifications to the libraries. The only downside is more maintenance work would be needed. If you are able to help us with that feel free to join the Discord and speak to either Polar or MattsCreative. They are the lead contributors so if you want to become a contributor those are the people to speak to.

**Comment by Polarzincomfrio** [comment]
Just as a follow up on the PR itself, we haven't got into analysing the PR 'till now, due to lack of time, it will be reviewed tomorrow by me or some other dev to check, due to the size of the pr it will take some time so, thanks for the patience

**Pull request merged**
