### PR TITLE
Android: Add Texture Sampling settings UI

### LINKED ISSUE #494: Request for Texture Sampling support for Android
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I would like to request that the texture sampling feature from the desktop version be ported to the Android version as well.

Just in case, I'm referring to this option here:
348562181-4c783bf8-9266-4949-87c6-4005749bdda9

### Why would this feature be useful?

Having the option to choose nearest neighbor for texture sampling makes many games look far better when upscaling, as most will have a blurry HUD, etc. by default otherwise.

### PR DESCRIPTION
**Pull request by rtiangha**
Should close #494 but I haven't tested it/use it much and I don't know if it'll work across different GPUs. Seems to work fine on my S21's Adreno 660. I added a new "Advanced" header in the Graphics section to match how it's categorized in the Desktop UI, but I have no strong feelings on where it ultimately lives.

Screenshot_20241007_070623_Lime3DS

### CODE REVIEW

**Comment by Tathagata-0** [comment]
Thanks for this PR! I tried it out on my phone (S24 Ultra, Adreno 750) and Odin 2 Mini (Adreno 740). On both, this option works great on OpenGL, but it didn't work on Vulkan. Here's a log from my phone if it helps:

[lime3ds_log.txt](https://github.com/user-attachments/files/17281699/lime3ds_log.txt)

(For context on the weird file path in the log, that's because it contains Japanese characters).

**Comment by rtiangha** [comment]
It didn't work at all under Vulkan? It might just be incompatible; all this PR is is an interface to the existing functionality; basically frontend UI stuff and it doesn't touch the rendering backend at all.

But since you've got an Adreno, have you tried one of the 3rd party custom Turnip drivers (or system pulled Qualcomm drivers from other devices)? You might get better results.
https://github.com/v3kt0r-87/Mesa-Turnip-Builder/releases
https://github.com/K11MCH1/AdrenoToolsDrivers/releases

Edit: Although I don't really use this feature at all so I don't know much about it. Does anyone out there know if it works properly on Vulkan in the Desktop app? If not, then that would explain things and I can edit the description to say it's OpenGL/ES only.

Edit 2: Well, after looking through the code, there are TextureFilter methods for both OpenGL and Vulkan, so in theory, it should work in Vulkan mode too. Whether or not it works properly is a different question. More testers needed for both Desktop and Android, I guess, although fixing any backend rendering issues would be outside the scope of this particular PR.

**Comment by Tathagata-0** [comment]
Yeah, I double checked and it works for me on the Desktop version (on Linux at least, I don't have a Windows machine to try).

Thank you for mentioning the turnip driver, I had forgotten about it. I gave that a try and it works with Vulkan on both of my Android devices! I guess maybe it's a Qualcomm driver issue.

**Comment by rtiangha** [comment]
Well it's good to have confirmation, then. We'll just blame it on crappy stock drivers from the manufacturer(s). 😝

**Comment by OpenSauce04** [comment]
Rebased for Azahar in #603

**Pull request closed without merging**
