### PR TITLE
Fixes to Actions

### PR DESCRIPTION
**Pull request by ayrudev**
I've managed to fix the Linux Builds and commented out MSYS2 build until it is fixed and working

### CODE REVIEW

**Comment by BlurrySquire** [comment]
The changes look good to me. I've closed my merge request, so I can take a fork of the repo when builds work properly.

**Comment by ryzendew** [comment]
yes everything built but one last request could you fix linux source?

**Comment by Polarzincomfrio** [comment]
> yes everything built but one last request could you fix linux source?

The "source" job is skipping because of a condition that checks if there's no pull request head reference (if: ${{ !github.head_ref }}). This basically means it won't run when there's a pull request going on.

Usually, this job kicks in when someone pushes changes directly to the repository without using a pull request. It's like a safety net for those quick fixes or direct maintenance tasks. So, if you see it skipping, it's probably because there's a pull request in action, and the workflow is set up to handle that separately.

**Comment by ayrudev** [comment]
> yes everything built but one last request could you fix linux source?

In the workflow file, there's this line:
```if: ${{ !github.head_ref }}```
This line basically means, "only run this job if there's no pull request happening.
That's why it skipped, it recognized that this is a pull request and skipped

**Pull request merged**
