### PR TITLE
Corrected overzealous removal of SDL2 frontend

### PR DESCRIPTION
**Pull request by OpenSauce04**
Follows on from and corrects the issues present in #413

When creating the PR mentioned above, I unintentionally removed more functionality from the emulator than I realized. This was due to my false assumption that SDL2 was only used for the CLI executable, when it was in fact used for a couple of other aspects of the emulator which didn't make themselves immediately obvious during my testing.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
@rtiangha @BlurrySquire Can both of you please verify that the issues you experienced previously have been resolved?

**Comment by BlurrySquire** [comment]
Sure. Perfect timing actually because my internet just came back up. If I remember I'll check when the ci job completes.

**Comment by OpenSauce04** [comment]
License warnings are to be ignored due to all changes simply being code reversions

**Comment by rtiangha** [comment]
Just popping in between things to say that my controller works again; have to run off again so I haven't tested anything else though but if it's just a simple revert, I wouldn't anticipate any other issues.

**Comment by BlurrySquire** [comment]
My controller is now working for me.

**Review by rtiangha — APPROVED** [review]
LGTM.

**Pull request merged**
