### PR TITLE
lime_qt: Fix order of Texture Filter drop-down menu

### LINKED ISSUE #450: xBRZ not working properly as it did previously in Citra
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2118

### Description of Issue

The xBRZ filter seems to just have sharp pixels instead of the expected smoothing. I use the Auto (Window Size) internal resolution. This seems to mostly affect the bottom screen.
xBRZ-in-Lime

### Expected Behavior

The expected behavior (as it was in Citra) is for a smoothed out image. Same settings with the internal res being Auto.
xBRZ-in-Citra

### Reproduction Steps

Open a game and enable xBRZ texture filtering.

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/17080803/lime3ds_log.txt)

### System Configuration

CPU:11th Gen Intel Core i5-1135G7
GPU/Driver:Intel Iris Xe Graphics/Mesa drivers
RAM: 8gb
OS: Arch Linux

### PR DESCRIPTION
**Pull request by rtiangha**
Make the front end match the order of the back end. Fixes #450 

New screenshot:
texturefilter

### CODE REVIEW

**Comment by OpenSauce04** [comment]
What's with the change in label for the Anime4K, xBRZ and Nearest Neighbor?

**Comment by alex100306** [comment]
From my understanding the Nearest neighbor option for that dropdown didn't exist in the backend, it was just in the dropdown options itself. As for the others I'm not sure why they were changed because I'm just the one who made the issue for the dropdown being wrong.

**Comment by rtiangha** [comment]
See #450 for the discussion.

The actual order is supposed to be

```
enum class TextureFilter : u32 {
    NoFilter = 0,
    Anime4K = 1,
    Bicubic = 2,
    ScaleForce = 3,
    xBRZ = 4,
    MMPX = 5,
};
```

I used the full names from the Android `strings.xml` (cross referencing with Google to verify their actual names).

**Comment by OpenSauce04** [comment]
I'm not sure that the full names are really needed, it just makes them unnecessarily long.

As for MMPX, have we determined if that texture filter is even working correctly? I saw the screenshot in the original post, and that is absolutely not what MMPX looks like.

**Comment by rtiangha** [comment]
Your call. I've seen the full names used in other emulators, but I'm not particularly attached to them.

As to whether MMPX works correctly in the first place, I have no idea. That's just how they're listed in `settings.h`. I read that Nearest Neighbor didn't look so hot to begin with, so maybe that's what's MMPX is. However, the Android `strings.xml` has it listed as `<string name="mmpx">MMPX</string>` so functionality aside, I assume the label is intentional.

Edit: Here's every listing of mmpx in the codebase; I assume the original devs meant it to be MMPX, even if it doesn't work correctly.

```
[reg@PROBOOK430-G4 Lime3DS]$ grep -ri mmpx src
src/android/app/src/main/res/values/arrays.xml:        <item>@string/mmpx</item>
src/android/app/src/main/res/values/strings.xml:    <string name="texture_filter_description">Enhances the visuals of games by applying a filter to textures. The supported filters are Anime4K Ultrafast, Bicubic, ScaleForce, xBRZ freescale, and MMPX.</string>
src/android/app/src/main/res/values/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-de/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-es/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-fr/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-pt/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-ru/strings.xml:    <string name="mmpx">MMPX</string>
src/android/app/src/main/res/values-zh/strings.xml:    <string name="mmpx">MMPX</string>
src/common/settings.cpp:    case TextureFilter::MMPX:
src/common/settings.cpp:        return "MMPX";
src/common/settings.h:    MMPX = 5,
src/lime_qt/configuration/configure_enhancements.ui:             <string>MMPX</string>
src/video_core/host_shaders/CMakeLists.txt:    texture_filtering/mmpx.frag
src/video_core/renderer_opengl/gl_blit_helper.cpp:#include "video_core/host_shaders/texture_filtering/mmpx_frag.h"
src/video_core/renderer_opengl/gl_blit_helper.cpp:      mmpx_program{CreateProgram(HostShaders::MMPX_FRAG)},
src/video_core/renderer_opengl/gl_blit_helper.cpp:    case TextureFilter::MMPX:
src/video_core/renderer_opengl/gl_blit_helper.cpp:        FilterMMPX(surface, blit);
src/video_core/renderer_opengl/gl_blit_helper.cpp:void BlitHelper::FilterMMPX(Surface& surface, const VideoCore::TextureBlit& blit) {
src/video_core/renderer_opengl/gl_blit_helper.cpp:    SetParams(mmpx_program, surface.RealExtent(false), blit.src_rect);
src/video_core/renderer_opengl/gl_blit_helper.cpp:    Draw(mmpx_program, surface.Handle(), draw_fbo.handle, blit.dst_level, blit.dst_rect);
src/video_core/renderer_opengl/gl_blit_helper.h:    void FilterMMPX(Surface& surface, const VideoCore::TextureBlit& blit);
src/video_core/renderer_opengl/gl_blit_helper.h:    OGLProgram mmpx_program;
```

**Comment by OpenSauce04** [comment]
For reference this is what MMPX is supposed to look like



The screenshot in the original issue absolutely looks like Nearest Neighbor, and it looks the same way on my end, so perhaps the MMPX label is simply incorrect?

There is also the consideration that without this there simply wouldn't be an option for Nearest Neighbor scaling, which would be strange

**Comment by rtiangha** [comment]
Perhaps Nearest Neighbor is the common name? FWIW, PabloMK7's branch has it as MMPX too. Am not at home right now so I can't check what the last Citra Nightly had it listed on the QT frontend.

**Comment by OpenSauce04** [comment]
As shown in the above image, MMPX looks very different to Nearest Neighbor

**Comment by alex100306** [comment]
latest citra qt has it listed as mmpx with no nearest-neighbor option.
screenshot-2024-09-21-22-24-19

**Comment by OpenSauce04** [comment]
Moving this to 2119 so we have more time to figure out what's going on with the MMPX thing.

**Comment by OpenSauce04** [comment]
On further investigation, it turns out that this texture filter does actually work as intended on desktop, but on Android it appears to use nearest neighbor scaling for whatever reason.

Amusingly, this means that both the desktop *and* mobile labels are currently incorrect, as desktop uses MMPX and is labelled as nearest neighbor, and Android is the opposite.

**Comment by OpenSauce04** [comment]
I did have a look at the GLSL code for the MMPX implementation, and it does seem to making some attempt to implement the MMPX scaling algorithm, so it seems that this is a case of the code simply not working correctly rather than the code being mislabelled. I'll keep looking into this.

**Comment by OpenSauce04** [comment]
I'm going to merge this now because the MMPX thing is a seperate problem to the list order. I will open a new issue which describes the texture filter not working correctly.

**Review by OpenSauce04 — APPROVED** [review]

**Pull request merged**
