### PR TITLE
Don't tie hotkeys to only the main window

### LINKED ISSUE #278: Many hotkeys do not have equivalent functionality when the secondary window is focused
### Issue

These only work while the primary window is focused.
Examples of hotkeys that do not function include 'Exit Fullscreen' and 'Audio Mute/Unmute'

### PR DESCRIPTION
**Pull request by OpenSauce04**
Closes #278

This PR changes `link_action_shortcut` to link all hotkey actions to the secondary window as well as the primary one.

An optional boolean `primary_only` has been added to `link_action_shortcut` when it is necessary to seperate primary and secondary window hotkeys. Currently this is only used for the fullscreen binding, as a different procedure is used for each window.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
This is currently marked as a draft because I'm figuring out how to get around `HotkeyRegistry::GetHotkey` being implemented stupidly and making multi-window shortcuts a pain.
Some hotkeys use `QShortcut` instead of `QAction`, and the former are still trapped on the primary window for this reason.

**Comment by OpenSauce04** [comment]
@rtiangha are you available to review this PR?

**Comment by rtiangha** [comment]
I'll have some time after the long weekend; I have some people visiting from out of town right now.

**Comment by OpenSauce04** [comment]
@rtiangha Did plans change? Please let me know, as I would like to merge this soon to meet the forthcoming 2117 milestone.

**Comment by ghost** [comment]
The feature works as intended , tested with the swap screen hotkey before and after

As for the code, i don't see anything wrong with ti as far as I can tell

**Review by ghost — APPROVED** [review]

**Pull request merged**
