### PR TITLE
Cleanup Theme Colors

### PR DESCRIPTION
**Pull request by ghost**
On https://github.com/Lime3DS/Lime3DS/pull/350 a new settings entry for static / pre-set colors was added
On light mode these colors looked fine but on dark mode they are WAY too undersaturated making it hard to tell the difference between red / pink / orange and blue / violet even on an AMOLED display with Samsung's oversaturated processing crap

This PR basically reworks all colors of dark mode to be more vibrant and actually separable from each other

Also cleaned up some (to my knowledge) unused colors, literally no difference after removing these

### CODE REVIEW

**Comment by ghost** [comment]
If you aren't a fan of the low contrast between elements, i can easily change the app to have a darker background and for the items color to have the main accent color 

Green theme as an example 


Screenshot of Lime3DS

Screenshot of Seal Preview

**Comment by OpenSauce04** [comment]
> If you aren't a fan of the low contrast between elements, i can easily change the app to have a darker background and for the items color to have the main accent color

This won't be necessary

**Comment by OpenSauce04** [comment]
I think the vividness of these colours is a bit too much. I don't see a particular issue with the current colours, as the purpose of these themes is to add a subtle touch to the interface.

Additionally, the tertiary colours should not be removed, even if they aren't currently used in the interface, as they are part of Android convention.

Regardless, thanks for the suggestion.

**Comment by ghost** [comment]
I missed this totally but aight

**Pull request closed without merging**
