### PR TITLE
Added badge for Google Play and changed the Flathub icon to a .svg

### PR DESCRIPTION
**Pull request by ayrudev**
This PR has been made to be merged once the Google Play release is officially out

### CODE REVIEW

**Comment by ghost** [comment]
I don't think obtanium is needed anymore

image

**Comment by BlurrySquire** [comment]
> I don't think obtanium is needed anymore
> 

I still think we should list it as an option since we distribute the apk on releases anyway.

**Comment by ghost** [comment]
Wiki perhaps 

Not needed on the readme tho

**Comment by BlurrySquire** [comment]
> Wiki perhaps
> 
> Not needed on the readme tho

Agreed. On the wiki is fine, we could list it as alternate install options maybe?

**Comment by ghost** [comment]
Yes

**Comment by OpenSauce04** [comment]
> I don't think obtanium is needed anymore

It will still be included on the readme as a secondary option alongside downloading the APK. Some users use devices or versions of Android which do not have the Google Play Store, either by limitation or by choice. It is important for these users to have an easy method of upgrading available and visible.

**Comment by ghost** [comment]
>  Some users use devices or versions of Android which do not have the Google Play Store, either by limitation or by choice. It is important for these users to have an easy method of upgrading available and visible.
> 

Most of them are probably using a third-party frontend for gPlay like Aurora Store

I really believe it doesn't need to take that much space,  at most a link to a wiki article

**Comment by DavidRGriswold** [comment]
I think I agree, only because I have noticed many users have been confused by that part of the readme. I think a line like "If you do not have access or would prefer not to use the Play Store, you could also use Obtainium as outlined in the wiki here." Would be appropriate though.

**Pull request closed without merging**
