### PR TITLE
citra_qt: Add support for favorites, desktop shortcuts, and play time tracking

### LINKED ISSUE #123: Track playtime on each game
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A feature to track how many hours and minutes you've been playing on each individual game

### Why would this feature be useful?

Would tell people their total playtime on each game

### PR DESCRIPTION
**Pull request by rtiangha**
I had originally wanted to do this as four separate PRs since it adds four features, but each commit built upon the last one that it was easier to submit it as a set instead.

This PR is taken from the [list of Pull Requests](https://web.archive.org/web/20240304201042/github.com/citra-emu/citra/pulls) that never had a chance to make it into Nightly or Canary before the shutdown (see the original by FearlessTobi [here](https://web.archive.org/web/20240212144630/https://github.com/citra-emu/citra/pull/7423)).

It adds four features to the Lime3DS QT interface:
* Cleans up the right click menu by organizing common things into sub-menus
* Adds the ability to favourite games so that they appear at the top of the games list
* Adds the ability to add desktop or application menu shortcuts for games
* Adds the ability to track the play time of games in the UI (Fixes #123 )

Here is what it looks like:
playtime
desktop

I've been using it for a few weeks now on Windows and it seems to work fine. It could use some testing on Mac and Linux though, since I don't have access to those sorts of machines. Specifically, confirmation if the creation of desktop or application menu shortcuts work on those platforms (I'm not sure if the paths are properly detected or set based on the initial commit; if not, that'll have to be figured out or maybe removed and fixed later to push this out quicker. Also not sure if it'll work properly across different Linux distributions or desktop environments).

### CODE REVIEW

**Comment by OpenSauce04** [comment]
I have yet to review the code or functionality of this pull request, but I am fine with all 4 of the primary changes being presented here on paper

**Comment by OpenSauce04** [comment]
On Windows 11, I have successfully tested all changes here
On Linux however, I managed to get the new right click, the shortcuts, and the favourite games section to work, but the "Play time" section does not exist

**Comment by OpenSauce04** [comment]
Oh, it turns out that the play time section was there, it was just off the right side of the screen, and I had to scroll horizontally to see it.
I guess this is an issue with existing installations, as on Windows I had deleted the Citra home folder before testing this PR.
Would there be a clean way of resetting this layout information for people updating from a previous version?
image

**Comment by rtiangha** [comment]
I had the same issue regarding having to resize the column to be able to see it. I'm not sure if there's a(n easy) way to reset it on an old installation without deleting settings; I can look into it but I wouldn't get my hopes up. It's an easy workaround anyway (i.e. just manually resize) and can be mitigated with some documentation in the Release Notes, but that's just my opinion.

**Comment by rtiangha** [comment]
But I did want to know: Did creating shortcuts work under Linux? I'm not 100% confident it'll work across different desktop environments (ex. QT/KDE vs Gnome, etc), but I can't test that. Ditto for MacOS.

**Comment by OpenSauce04** [comment]
Yes, the shortcuts work as expected under Linux, although I tested it on a TWM by launching the generated shortcut through the terminal, so I am currently unsure of interactions across actual DEs. I will test this at a later time
@Polarzincomfrio Has the ability to test on MacOS
On the topic of how the layout data may be reset, would it be possible to detect if there is no layout information for the Play Time tab, and if that's the case, reset the layout? Hypothetically this should only happen if the user is upgrading from a version where the Play Time tab didn't exist

**Comment by rtiangha** [comment]
OK, I think I found a solution. On start up, it'll resize all of the columns except for the first one to fit the max size of their contents. That implies things get reset each time the program starts, but since everything but the Name column is small anyway, I don't think people will complain because they'll still be able to see the data (and I doubt they'd make those particular columns larger anyway) and it'll still keep whatever size people set Name to, which I assume is the one most people would want to change anyhow.

The last column (whatever it ends up being if people add more columns in the future) is set to stretch and fill the rest of the remaining space.

**Comment by ayrudev** [comment]
> Yes, the shortcuts work as expected under Linux, although I tested it on a TWM by launching the generated shortcut through the terminal, so I am currently unsure of interactions across actual DEs. I will test this at a later time @Polarzincomfrio Has the ability to test on MacOS On the topic of how the layout data may be reset, would it be possible to detect if there is no layout information for the Play Time tab, and if that's the case, reset the layout? Hypothetically this should only happen if the user is upgrading from a version where the Play Time tab didn't exist

Haven't been able to test it out just yet, gonna test it tomorrow once i get a chance to use the Mac

**Comment by OpenSauce04** [comment]
1e925bd works as expected on my end

**Comment by OpenSauce04** [comment]
Patiently waiting on Mac testing before a merge

**Comment by OpenSauce04** [comment]
Waiting on Mac testing whenever you're available @Polarzincomfrio

**Comment by ayrudev** [comment]
> Waiting on Mac testing whenever you're available @Polarzincomfrio 

oh yh, it works fine just gotta find someone with an ARM mac, since i don't have one, just an Intel one

**Comment by rtiangha** [comment]
To be honest, it's more the desktop environment than the architecture. I just wanted to make sure the creation of shortcuts worked on MacOS; the hardware it's running on probably doesn't matter; if it works on x86_64, it'll probably work on arm. If people are happy with this, it's probably safe to push out.

**Comment by OpenSauce04** [comment]
Alright, I'll complete my review either tomorrow or the day after
Sorry for the delay

**Review by BlurrySquire — APPROVED** [review]
I have tested this and favourites and shortcuts work well. This is a really useful addition.

**Comment by ryzendew** [comment]
image
Screenshot from 2024-05-11 15-58-58

Tested it on windows and linux both work fine

**Review by ryzendew — APPROVED** [review]

**Review by OpenSauce04 — APPROVED** [review]
All looks fine to me. Obviously checking over a PR this large which implements multiple changes simultaneously is difficult, so I was only able to look over everything at a pretty surface level, however nothing jumped out as obviously wrong or problematic.

Again, sorry for taking so long to get to this. Having a hard time with work-life balance at the moment 😅 

PS. Not related to the PR content, but please disable forced commit signatures on your fork 🙂

Thanks for the contribution!

**Comment by rtiangha** [comment]
Merging the PR rather than using `git cherry-pick` for each commit should fix the Unverified issue. Or set up the Git client to automatically sign commits without having to specify the `-s` flag; it's super easy to set up.

https://gist.github.com/mort3za/ad545d47dd2b54970c102fe39912f305

**Pull request merged**
