### PR TITLE
Fix for full screen Smash Bros crash in Vulkan

### PR DESCRIPTION
**Pull request by rtiangha**
It was discovered that one of the final [Canary](https://web.archive.org/web/20240304191750/https://github.com/citra-emu/citra-canary) pull requests (originally titled "`renderer_vulkan: Rewrite descriptor set management and various small fixes`" fixes a crash that occurs in Vulkan when switching to full screen in Smash Bros (and maybe some other games too). It never got a chance to be merged into the Nightly branch before the shutdown, so here is the patch set, lightly updated to work with the modern code base.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
@rtiangha Would you mind merging the master branch into your PR? I seem to not have permission to do so

**Comment by rtiangha** [comment]
Oh wow, not sure why the build is failing. Let me make sure I sync'd everything up correctly...

**Comment by rtiangha** [comment]
OK, this is weird. If you look at the Actions tab, _clearly_ it compiled cleanly when I submitted the request. But now it doesn't build against Master. Based on the commit titles in the changelog, there doesn't seem to be anything obvious so I'm going to have to dig really deep to see what changed. Give me some time.

**Comment by rtiangha** [comment]
Oh, I see what happened. Merging in the clang-format-18 stuff from Master _after the fact_ bashed some of the changes and reintroduced some old code that was no longer there.

Should be easy to fix. Give me some time.

**Comment by rtiangha** [comment]
There, that should do it.

**Comment by OpenSauce04** [comment]
I'll get to reviewing this tomorrow evening, sorry for the delay

**Comment by OpenSauce04** [comment]
I ended up getting occupied IRL, and will have to push back review by another day. I should be available tomorrow evening for real this time

Again, sorry for the delay

**Review by OpenSauce04 — APPROVED** [review]
LGTM. I've successfully confirmed that this fixes the crashing issue on SSB3DS
This PR is very large and seems to change a lot of parts of the Vulkan renderer's backend. It would be worth checking other previously problematic games and seeing if there are any other improvements here

**Comment by DonelBueno** [comment]
Great work, also fixed the crashes on Luigi's Mansion Dark Moon which were introduced by the last optimization from GPUCode.

**Pull request merged**
