### PR TITLE
3dsx: Minor cleanups and add argument support

### PR DESCRIPTION
**Pull request by rtiangha**
This was a PR by [GPUCode/raphaelthegreat](https://github.com/raphaelthegreat/citra/commits/3dsx-args/) that actually made it into the [final Canary](https://web.archive.org/web/20240302083829/https://github.com/citra-emu/citra-canary) before the shutdown . Unfortunately, the Wayback Machine didn't archive the original pull request, but from what I can tell, it does what it says in the subject line: Cleans up the code a bit and adds support for arguments for 3dsx plugins. I had ported it to Lime3DS to try to help someone who was having 3dsx issues but it didn't seem to help them, but the work was already done so may as well submit a PR.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
This code appears to make 3dsx executables not function correctly. I have used a homebrew app called [TSI9](https://github.com/JohnodonCode/TSI9) to test.
On both the latest release and 7b25c1e, the program runs correctly, however when testing with this PR, only a black screen is displayed.

**Comment by rtiangha** [comment]
@OpenSauce04 OK, without knowing much about 3DS homebrew myself, I think I need a sanity check. Can you test [this custom version of Citra](https://github.com/rtiangha/bravely-offline-citra/releases/tag/v2024-05-23a) that has the patch installed? Because if it doesn't work there, then I'll assume it didn't work entirely correctly in the first place.

And can you test one of the artifact builds based on the last commit I made to this thread (mistakenly; I meant to do it on a dev branch but serves me right for coding late at night)? Because again, without knowing much about how 3DS homebrew works, it's the only thing I can think of changing because on the surface, the code looks good to me.

**Comment by OpenSauce04** [comment]
> Can you test [this custom version of Citra](https://github.com/rtiangha/bravely-offline-citra/releases/tag/v2024-05-23a) that has the patch installed?

The AppImage crashes instantly, not sure why
Upon building from scratch from the latest commit, the homebrew works fine in this fork

**Comment by rtiangha** [comment]
No, you're right. It doesn't even run on the final Canary where it was supposedly introduced. Maybe it works for other 3dsx plugins, but the bottom line is that this plugin works on versions without the patch installed.

Unfortunately, I don't know enough about 3DS homebrew to be able to debug and fix GPUCode's code and I don't really have the time to do a deep dive on it myself. So unless another person wants to take a stab at this, I'm happy with it not being merged. Feel free to close this if no one else wants to grab the baton.

**Pull request closed without merging**
