### PR TITLE
Update on README.md

### PR DESCRIPTION
**Pull request by ayrudev**

### CODE REVIEW

**Comment by Polarzincomfrio** [comment]
I noticed that the `release` job in the GitHub Actions workflow appears to be getting skipped, even when all other jobs succeed. After reviewing the workflow configuration, I wanted to provide some clarification on why this might be happening and how we can ensure the `release` job runs as expected in the future.

The reason the `release` job is getting skipped is due to its conditional execution based on the `github.ref` starting with `'refs/tags/'`. This condition ensures that the `release` job runs only when a tag is pushed to the repository. If the trigger event does not involve pushing a tag, such as in the case of regular branch pushes or pull requests, the `release` job will be skipped.

To make the `release` job work as intended, here's what we can do:

1. **Creating and Pushing Tags**: If you're aiming to trigger the `release` job through a tag push, you can manually create a tag and push it to the repository. You can do this using the following commands:

   ```
   git tag <tag_name>
   git push origin <tag_name>
   ```

   Replace `<tag_name>` with the name you want to give to your tag. Ensure you have appropriate permissions to push tags to the repository.

2. **Automating Tagging**: Alternatively, if you prefer automating tag creation based on specific criteria, we can modify our CI/CD pipeline to automatically create and push tags when certain conditions are met. This could involve tagging successful builds on specific branches or meeting other predefined criteria.

3. **Exploring Other Triggers**: If the goal is to trigger the `release` job based on events other than tag pushes, we can explore other triggers such as pull request events. Although the `release` job cannot directly push a tag as part of a pull request, we can still perform certain actions based on pull request events and adjust our workflow accordingly.

If you have any questions or need further assistance with this, feel free to reach out. Let's work together to ensure our CI/CD pipeline meets our requirements effectively.

**Comment by ayrudev** [comment]
I noticed that the `release` job in the GitHub Actions workflow appears to be getting skipped, even when all other jobs succeed. After reviewing the workflow configuration, I wanted to provide some clarification on why this might be happening and how we can ensure the `release` job runs as expected in the future.

The reason the `release` job is getting skipped is due to its conditional execution based on the `github.ref` starting with `'refs/tags/'`. This condition ensures that the `release` job runs only when a tag is pushed to the repository. If the trigger event does not involve pushing a tag, such as in the case of regular branch pushes or pull requests, the `release` job will be skipped.

To make the `release` job work as intended, here's what we can do:

**Creating and Pushing Tags**: You can manually create a tag and push it to the repository. You can do this using the following commands:

   ```
   git tag <tag_name>
   git push origin <tag_name>
   ```

   Replace `<tag_name>` with the name you want to give to your tag.

**Comment by ayrudev** [comment]
Also, on release ios will skip since it probably wasn't ready for use

**Comment by ayrudev** [comment]
Also, if u can, send ur discord here so we can keep on contact

**Comment by ryzendew** [comment]
i want to keep the link to the other fork for release and i added my release page back now that more things are fixed

**Comment by ayrudev** [comment]
there you go

**Pull request merged**
