### PR TITLE
Audio & GPU fixes

### PR DESCRIPTION
**Pull request by KyloRen97**

### CODE REVIEW

**Comment by KyloRen97** [comment]
This fixes some minor bugs in the HLE audio core and the GSP module. I had these on one of my forks and was planning to PR them but Citra went down all of a sudden and yeah...

The DSP fix is notable in games like Captain Toad which use biquad filtering. Without it, the audio presents an LPF-like behavior and higher pitches noises won't sound correct

**Comment by askotx** [comment]
Maybe you could try to add this PR in PabloMK7's repository: 
https://github.com/PabloMK7/citra

**Comment by ryzendew** [comment]
it's building now and if it builds i will merge

**Comment by Miguel-hrvs** [comment]
In my fork I get a black screen in pokemon moon if I apply your gsp gpu fix

**Comment by PabloMK7** [comment]
@KyloRen97 I don't get the audio sample fix, what did you base the change on? The maximum signed s16 value is 32767, not 32768. If a sample becomes 32768 then it will overflow to -32768. In fact, you mention that the game uses biquad filtering, but your change applies to the simple filter, not the biquad one.

**Pull request merged**
