### PR TITLE
Android haptic feedback

### PR DESCRIPTION
**Pull request by gperrio**
Add haptic feedback to the overlay controls.
Can be disabled in the overlay menu.

### CODE REVIEW

**Review by ayrudev — COMMENTED** [review]
The code itself LGTM, however I can't get it working when testing on my Samsung A54

**Comment by gperrio** [comment]
You mean it just has no effect?

**Comment by ayrudev** [comment]
> You mean it just has no effect?

yep

**Comment by gperrio** [comment]
Is it disabled at the system level maybe?

**Comment by ayrudev** [comment]
> Is it disabled at the system level maybe?

oh, my bad, i had system touch vibrations off lol

**Review by ayrudev — APPROVED** [review]
LGTM and now it works lmao mb

**Comment by OpenSauce04** [comment]
I am also unable to feel any haptic feedback, although I do have vibrations enabled and can feel it when I use my keyboard, so I don't think this is a me issue
The setting is enabled in the overlay settings

**Comment by gperrio** [comment]
Anything haptic related in the logcat?

**Comment by OpenSauce04** [comment]
I don't see anything related to haptics, no

**Comment by OpenSauce04** [comment]
Nothing except `haptic generated by application` whenever a button is pressed
Edit: I also see `semGetSupportedVibrationType: ret=1`

**Comment by gperrio** [comment]
What device are you using?

**Comment by OpenSauce04** [comment]
I am testing this on a Galaxy A52 5G

**Comment by OpenSauce04** [comment]
Just to double check, I went through and enabled every vibration-related setting I could find and turned my vibration intensity as high as it can go, still nothing

**Comment by gperrio** [comment]
If you replace VIRTUAL_KEY with KEYBOARD_TAP, does it change anything?

**Comment by OpenSauce04** [comment]
It doesn't seem to make any difference, no
For the sake of completeness, I also tried replacing `VIRTUAL_KEY_RELEASE` with no luck

**Comment by gperrio** [comment]
Can you try this app?
https://play.google.com/store/apps/details?id=com.janeproject.haptic_checker

**Comment by OpenSauce04** [comment]
I am unable to feel the haptics mentioned above in this app for whatever reason
Some of them work, some don't. None of the ones used in this PR do

**Comment by OpenSauce04** [comment]
Looking online, this seems like a skill issue on Samsung's part rather than an issue on this PR. For this reason, I will request for @BlurrySquire to review this PR in my place, as I want to keep my main phone on release only. Outside of the functionality, the code looks fine to me

@BlurrySquire Once you have reviewed this and verified its functionality, please squash commit this to master

**Comment by gperrio** [comment]
Can you tell me which ones work on your A52?

**Comment by OpenSauce04** [comment]
As this appears to be a configuration issue on Samsung's part rather than an issue in the code itself, it shouldn't affect the code, especially as Polar's A54 appears to be working fine

**Comment by BlurrySquire** [comment]
I have an A51. It's 1am here I'll test it tomorrow morning.

**Comment by BlurrySquire** [comment]
No luck with my A51. Turned vibration up to the max. Still nothing. I also checked to make sure it was on. I don't get it either on my keyboard. (Yeah i use a custom one, it is gboard by google) even though I have it enabled. On system vibration I have all of them turned on. I'm gonna check the developer settings. Then I will get back to you. Like @OpenSauce04 said this seems like a skill issue on Samsung's part.

**Comment by BlurrySquire** [comment]
No luck. The only haptic feedback option that worked was ``LONG_PRESS`` on the haptic checker app.

**Comment by BlurrySquire** [comment]
@Polarzincomfrio what setting did you enable? I've got a similar phone (A51) but cannot get it to work. I have all the options checked in the system vibrations settings.

**Review by BlurrySquire — APPROVED** [review]
Doesn't work for me but that is because of Samsung as I've tested my phone's haptic feedback on another app. Apart from that everything looks good.

**Comment by ayrudev** [comment]
im just waiting it to build before i squash and merge it

**Pull request merged**
