### PR TITLE
Release versioning fixes

### PR DESCRIPTION
**Pull request by OpenSauce04**
This pull request fixes the version numbering system to correctly detect when a tagged release has been made

In short, this was caused by several checks which served to detect whether a release was based on Nightly or Canary, and as we use neither, our releases were being versioned as if they were regular commits

Additionally, I also changed how Lime3DS's release package filenames are formatted:
image
The format for the release packages now uses the tag name as a suffix and omits the date and commit from the filename.

The directory contained within the release packages has also been updated to contain a `lime` prefix before the tag
image

These formatting changes doesn't affect the source archives, which still use the same format as always

### CODE REVIEW

**Comment by OpenSauce04** [comment]
I have updated the formatting to use `lime3ds` instead of `lime` for consistency

**Comment by Polarzincomfrio** [comment]
Looks fine to me

**Comment by Polarzincomfrio** [comment]
Looks fine to me

**Review by ayrudev — APPROVED** [review]
Looks fine to me

**Pull request merged**
