### PR TITLE
Add quicksave / quickload new savestate slots and hotkeys 

### PR DESCRIPTION
**Pull request by ghost**
This is mostly just 
https://github.com/Lime3DS/Lime3DS/pull/280 but rebased into the current codebase and very small cleanup done by me

The code was clean enough. It actually simplified the Android save state logic a bit, and the feature works mostly without any issues on both pc and Android 

Idk why this was sitting in an outdated branch as a draft, but since i don't have  write access to it , i just decided to reopen

### CODE REVIEW

**Comment by ghost** [comment]
Note: Seems there are still issues with spamming the hotkey on Android at least 

Now i hope the toast is enough for most users not to go and spam the hotkey 

The UI slots don't need to disable while saving because saving the state is very fast, so msot users shouldn't run into issues. The problem is laoding it 

Perhaps a way to prevent hotkeys for being spammed like a Timer would fix these issues

**Comment by kleidis** [comment]
Note: Seems tgere are still issues with spamming the hotkey on Android at least 

Now i hope the toast is enough for most users not to go ajd spam the hotkey 

The UI slots don't need to disable while saving because saving the state is very fast, so msot users shouldn't run into issues. The problem is laoding it 

Perhaps a way to prevent hotkeys for being spammed like a Timer would fix these issues

**Comment by DavidRGriswold** [comment]
The original question I posted in this branch still stands - will there be confusion between the Quick Save and Save In Oldest Slot features on desktop?

**Comment by ghost** [comment]
> The original question I posted in this branch still stands - will there be confusion between the Quick Save and Save In Oldest Slot features on desktop?

We may maybe remove the oldest slot hotkey 

Never saw this on any other emulator that i used personally 

But it really isn't conflicting. it just might be confusing to some 

So leaving it untouched wouldn't be a bad idea either 

I need opinions from all active contributors on this one

**Comment by OpenSauce04** [comment]
> We may maybe remove the oldest slot hotkey 

I have no opinion on this really. I would likely never use it, but I can also imagine it being something people use out of habit. I'll go with the general consensus. 

If it is removed, do it in another PR.

**Comment by DavidRGriswold** [comment]
I would never recommend removing something people might have gotten used
to. Rotating oldest slots is actually pretty different from a single quick
save.

**Comment by ghost** [comment]
> If it is removed, do it in another PR.

In that case, we need testers to test this to see if more bugs occur

**Pull request closed without merging**
