### PR TITLE
Icon change again.

### PR DESCRIPTION
**Pull request by BlurrySquire**
I have updated the icon again. This time it should be correctly sized. I went through many attempts of fixing it before realising you sent me an updated one on my previous pull request. I know I'm now a contributor but I'm still opening a pull request to make sure it works before committing directly.

### CODE REVIEW

**Comment by BlurrySquire** [comment]
Ok, well this didn't fix it. I'm gonna go an do some research on ways to fix it.

**Comment by BlurrySquire** [comment]
I might of fixed it. The icon has sizes 128x128, 196x196 and 256x256. It might be falling back on the smaller sizes so I'm gonna try with only 256x256.

**Comment by BlurrySquire** [comment]
Checking if it builds and works now.

**Comment by ryzendew** [comment]
[68747470733a2f2f692e696d6775722e636f6d2f41444a6a4d6e522e706e67_enhance_2x_obu_icon.zip](https://github.com/ryzendew/Lime-3DS-Emulator/files/14776457/68747470733a2f2f692e696d6775722e636f6d2f41444a6a4d6e522e706e67_enhance_2x_obu_icon.zip)
here i fixed the icon now i had to remove somethings

**Comment by BlurrySquire** [comment]
Ok i'll update it now.

**Comment by ryzendew** [comment]
image
looks good now

**Comment by BlurrySquire** [comment]
Ok, have you already committed it? If you have I'll close my pull request.

**Comment by ryzendew** [comment]
> Ok, have you already committed it? If you have I'll close my pull request.

nope just showing it on my end

**Comment by BlurrySquire** [comment]
Ok, we know this will work so we can just merge the pull request? Or should we wait for builds?

**Comment by ryzendew** [comment]
MAGICAL!!!

**Comment by ryzendew** [comment]
now discord RPC needs another update for the new icon

**Comment by ryzendew** [comment]
Lime

**Pull request merged**
