### PR TITLE
Android/ARM64: Optimize AreQuaternionsOpposite

### PR DESCRIPTION
**Pull request by Gamer64ytb**
Applies architecture-specific optimizations for ARM64 using NEON intrinsics, which enhances the performance of quaternion comparison by leveraging vectorized floating-point operations. Based on a old fix of weihuoya's citra.

Fixes Batman Arkham Origins: Blackgate deadlocks and maybe more games

### CODE REVIEW

**Comment by OpenSauce04** [comment]
I hate to ask, but have you tested this extensively to make sure it does what you think it does?
Do you have some numbers you can point at to back up that the performance is actually improved?
I don't want a repeat of the last few PRs.

**Comment by Gamer64ytb** [comment]
According to @kleidis testing and mine there seems to be no issues. About performance I'm not very sure because my device is too powerful to notice performance improvements, but a tiny bit of performance might be noticeable.

**Comment by OpenSauce04** [comment]
I want to see visual evidence that this code has a positive impact before going further.

**Comment by rtiangha** [comment]
I feel like this needs to be tested on an arm64 Mac first just to be sure. And maybe an arm64 Raspberry Pi or similar. Because of endian stuff.

**Comment by OpenSauce04** [comment]
This pull request has been closed due to contributions from the pull request author no longer being welcomed

**Pull request closed without merging**
