### PR TITLE
android: Fix pause emulator button crashes

### LINKED ISSUE #110: App crashes after pausing emulation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

Pausing/resuming emulation crashes Lime3DS. Sometimes it takes two or three pauses to crash the app but sometimes it crashes immediately.

### Expected Behavior

Pausing and resuming emulation should not crash the app.

### Reproduction Steps

1. Start a game
2. Pause emulation
3. Resume emulation
4. Go to step 2 if the app didn't crash already

### Log File

This crash doesn't produce any new entries in logfile

### System Configuration

CPU: Exynos 9810
GPU/Driver:
RAM: 4 GB
OS: Android 10

### PR DESCRIPTION
**Pull request by ghost**
This fixes the crash when passing and unpausing the emulator 

It actually checks if s_surf is not None before releasing it, which I assume was the reason it even crashed

Closes https://github.com/Lime3DS/Lime3DS/issues/110

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Is this not from https://github.com/mandarine3ds/mandarine/commit/a4ed30f6be2565a4f874a5e5425947a9f82534ac?

**Comment by ghost** [comment]
> Is this not from [mandarine3ds/mandarine@a4ed30f](https://github.com/mandarine3ds/mandarine/commit/a4ed30f6be2565a4f874a5e5425947a9f82534ac)?

I shared the code with him, and he took without author 

As a screenshot*

**Comment by OpenSauce04** [comment]
> > Is this not from [mandarine3ds/mandarine@a4ed30f](https://github.com/mandarine3ds/mandarine/commit/a4ed30f6be2565a4f874a5e5425947a9f82534ac)?
> 
> I shared the code with him, and he took without author
> 
> As a screenshot*

🙄

**Review by OpenSauce04 — APPROVED** [review]
Fixes the issue on my end, thanks for your contribution!

**Pull request merged**
