### PR TITLE
Rebrand: Replace remaining Citra references with Lime3DS

### LINKED ISSUE #307: "Save Screenshots To" path still set to old (Citra) user data directory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2116

### Description of Issue

The "Save Screenshots To" path is still set to the old (Citra) user data directory instead of the new one.

The only other reference I see to Citra is that the Username is still CITRA under the System settings.

### Expected Behavior

I expected the path to be changed to the new Lime3DS one.

### Reproduction Steps

Open Lime3DS 2116

### Log File

N/A

### System Configuration

N/A

### PR DESCRIPTION
**Pull request by rtiangha**
OK, here's my pass to complete the rebranding. The only thing I didn't touch was the web links because I didn't know where to point them to instead, although I did take the liberty to add more Wayback Machine links where applicable.

Edit: Hmm, not sure how to fix the lime-license error; don't know where it's pulling the `src/android/app/src/main/java/io/github/lime3ds/android/CitraApplication.kt` reference from so it can be renamed, but the file exists as `Lime3DSApplication.kt` in that directory.

Edit 2: Oops, didn't notice it touched `dist/compatability_list/compatability_list.json`. If that's maintained somewhere else, they may need to be synced (still seems to work, though).

### CODE REVIEW

**Comment by OpenSauce04** [comment]
> Hmm, not sure how to fix the lime-license error;

Ah, it's likely because I forgot to check that the changed file actually still exists. 🙃
Easy oversight and simple fix, I'll address it tomorrow.

**Comment by OpenSauce04** [comment]
I have now fixed the issue with the license header checker, although given the nature of this PR, I think it's safe to say the changes it is suggesting can be wholely ignored. When this is ready for merging, the license requirement will be bypassed.

**Comment by BlurrySquire** [comment]
> I have now fixed the issue with the license header checker, although given the nature of this PR, I think it's safe to say the changes it is suggesting can be wholely ignored. When this is ready for merging, the license requirement will be bypassed.

when i look at the details of the failed ci job it shows 1148 files with no license header. Should we check some of those files? Or is it just the checker being weird.

**Comment by OpenSauce04** [comment]
> when i look at the details of the failed ci job it shows 1148 files with no license header. Should we check some of those files? Or is it just the checker being weird.

Observe the number of files changed in this PR; This number of files being flagged makes perfect sense.
Also, the license checker is designed to find headers which need to be updated to include Lime3DS attribution, not files with a missing header.

**Comment by OpenSauce04** [comment]
Do you know what `dist/scripting/citra.py` does? I've never seen what it's used for.

Edit: After briefly checking online, it appears to be something used as an interface by users to interact with games programmatically using Python scripts. To avoid breaking any existing scripts, I will revert the changes in this file.

**Review by OpenSauce04 — APPROVED** [review]
All looks good to me. Looked through the change list and corrected anything which seemed off.

**Pull request merged**
