### PR TITLE
Various build fixes for GCC and Clang

### PR DESCRIPTION
**Pull request by rtiangha**
Here are a few things I encountered and fixed when playing around with PabloMK7's fork trying to update some of the submodules.

### CODE REVIEW

**Comment by ryzendew** [comment]
We are checking the builds out the AI part is not sitting well hold on

**Comment by ryzendew** [comment]
if you are in the discord let me know in gen chat

**Comment by rtiangha** [comment]
Thanks. I'm not on Discord much, but maybe I'll drop by when I have time. In the meantime, I think this should be enough for you guys to reactivate the msys2 build.

**Comment by rtiangha** [comment]
Fixes #21

**Pull request merged**
