### PR TITLE
Basic implementation of AC::ScanAPs and NWM_INF::RecvBeaconBroadcastData (squashed)

### PR DESCRIPTION
**Pull request by PTRCoder**
This is a reopened version of my previous pull request #394. My reason for redoing this was to clean up commit history (thank you to @rtiangha for explaining a nice way to mash the different trial & error commits together).

**TODO:**
- [ ] Implement `NWM_INF::RecvBeaconBroadcastData` independently of `NWM_UDS::RecvBeaconBroadcastData`
- [ ] Fix `unmapped WriteBlock` error when `ScanAPs` is called by a game
- [ ] Change approach of calling `NWM_INF::RecvBeaconBroadcastData` in `ScanAPs`

### CODE REVIEW

**Comment by rtiangha** [comment]
One more suggestion: The first line of the description is used as the title of the commit, so if these commits are grouped by some kind of similarity, it might be useful to have that appear in the title; that's why they're all named "Squashed commit of...". The editor that appears when you squash things can be used to add in a title if you want.

Anyway, looking forward to seeing where this leads. Someone else was working on something similar on PabloMK7's fork, but the branch was eventually deleted so maybe they didn't get very far (they were also using some kind of bin file for their data, but I couldn't figure out where they may have dumped it from). I managed to cherry-pick a copy before it disappeared, though.

https://github.com/rtiangha/bravely-offline-citra/commit/58599b47860bc16ed9c8e09a122fccecc0c16200

**Comment by PTRCoder** [comment]
Did that branch compile correctly and did it work as intended when paired with the data bin or was it still just a WIP?

**Comment by rtiangha** [comment]
Compile, yes. But since I couldn't figure out where they got the data file from, I couldn't test. Also, PabloMK7's branch when it comes to the AC stuff is a bit different from Lime3DS's as he [reverted a change](https://github.com/PabloMK7/citra/pull/5) that was introduced in upstream Citra pre Lime3DS because it was outputting incorrect values. I'm hoping your changes fix that; if they do fix whatever issues he was encountering, I hope you'll consider submitting your changes to his branch too.

**Comment by OpenSauce04** [comment]
Please rewrite the commit history to have proper commit messages and explain some method by which I can verify that this code is working as intended.

**Pull request closed without merging**
