### PR TITLE
Free up some RAM usage

### PR DESCRIPTION
**Pull request by Gamer64ytb**
Some users reported way better RAM usage after this.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
What is the rationale behind these changes? Why would they result in an improvement in RAM usage?

**Comment by Gamer64ytb** [comment]
microprofiles or debug asserts can take some RAM usage as well, so I removed some that are not-needed due to changes from before. On testing there are no issues as well

**Comment by OpenSauce04** [comment]
Have you measured how much RAM is saved when this change is used in practice?

**Comment by Gamer64ytb** [comment]
Appoximately, 1.5GB. According from some people tests.

**Comment by OpenSauce04** [comment]
Is that how much is saved, or how much the emulator uses overall?
That seems like a very large amount

**Comment by Gamer64ytb** [comment]
It is how much is saved. I saw from some videos and kleidis old testing

**Comment by OpenSauce04** [comment]
I'll have to check myself later on, that sounds way too good to be true

**Comment by BlurrySquire** [comment]
> Appoximately, 1.5GB. According from some people tests.

Whenever I use Lime3DS it uses about 1.5GB ram. So I don't see how it can save that much.

**Comment by BlurrySquire** [comment]
Also you removed ``DEBUG_ASSERT``. They are only included in debug builds iirc.

**Comment by BlurrySquire** [comment]
> Also you removed `DEBUG_ASSERT`. They are only included in debug builds iirc.

What I mean by only included in debug builds is that in release builds they just aren't compiled in. Removing these are going to make debugging a pain if we have to test in a debug build.

**Comment by BlurrySquire** [comment]
One last statement. What games were tested? Some games have much lower ram usage. For example, Mario and Luigi Superstar Saga uses about 650mb of ram. Whereas Luigi's Mansion Dark Moon uses about 1.2gb of ram.

**Comment by CheriCheriLady87** [comment]
> One last statement. What games were tested? Some games have much lower ram usage. For example, Mario and Luigi Superstar Saga uses about 650mb of ram. Whereas Luigi's Mansion Dark Moon uses about 1.2gb of ram.

Check RE Revelations 1

**Comment by BlurrySquire** [comment]
All builds failed.

**Comment by Gamer64ytb** [comment]
these actions errors seems from git clone failure, not related

**Comment by Gamer64ytb** [comment]
imagen

**Comment by BlurrySquire** [comment]
I looked and it was being unable to clone a third party library. Lets see if it works this time.

**Comment by OpenSauce04** [comment]
Codeberg is down; I will re-run the builds later when the issue is resolved

**Comment by BlurrySquire** [comment]
Oh no. [codeberg.org/soundtouch/soundtouch.git/](https://codeberg.org/soundtouch/soundtouch.git/). The site is down.

**Comment by BlurrySquire** [comment]
image
Top one is 2110, bottom is pull request. There is a drop in ram usage. I tested Luigi's Mansion: Dark Moon.

However I am unsure what MICROPROFILE_SCOPE does. So I won't be approving until we know what it does because it was removed.

**Comment by rtiangha** [comment]
Well, it's not a direct explanation, but you can kind of infer what it does from GPUCode/raphaelthegreat's description when he proposed replacing Microprofile with Tracy profiler.

https://web.archive.org/web/20240205164805/https://github.com/citra-emu/citra/pull/7416

Profiling is supposed to help with debugging and checking out performance, so there is some use to it. But if it is indeed what is causing memory to be eaten up, perhaps the calls should be surrounded by conditionals that you can set at compile time in case someone wants to activate that functionality for research purposes. Kind of like how you can set things to be a Debug compile or a Release compile by passing along a few cmake options.

Or if nobody cares, just take them all out, lol.

Edit: BTW, you activate it with `View->Debugging->Microprofile`

**Comment by Gamer64ytb** [comment]
So what do you guys prefer, do I just delete all microprofiles or I replace with this implementation?

**Comment by Algiuxs** [comment]
Maybe have two release with and without

**Comment by rtiangha** [comment]
Well, if anyone wants to play around with a Tracy version and see how it does with memory usage compared to the other builds, I've got one building here:

https://github.com/rtiangha/Lime3DS/actions/runs/8794880001

If people like it, I can submit a PR.

**Comment by OpenSauce04** [comment]
If this really is just used for debugging purposes and nothing else, I'm not against putting this behind debug builds
I don't believe it should be ripped out entirely though

Please update this PR accordingly. I will mark it as a draft for now; Mark the PR as ready for review when the changes have been made

**Comment by Gamer64ytb** [comment]
Updated.

**Comment by BlurrySquire** [comment]
> If this really is just used for debugging purposes and nothing else, I'm not against putting this behind debug builds I don't believe it should be ripped out entirely though
> 
> Please update this PR accordingly. I will mark it as a draft for now; Mark the PR as ready for review when the changes have been made

I agree. We just make another compile flag that keeps them in or out for only compile time. basically a ``constexpr`` if statement for each usage.

**Comment by OpenSauce04** [comment]
Oh I missed that commit earlier which made the changes I described, my bad

**Comment by BlurrySquire** [comment]
> Oh I missed that commit earlier, my bad

Could you clarify? Also I think we should keep the changes requested since we probably want this to be set through a compiler argument, which hasn't been done yet I don't think.

**Comment by OpenSauce04** [comment]
> Could you clarify?

I assumed that the earlier commit b578ee5 had already implemented the previously requested changes, as Gamer64 simply merged master into the branch and then said he had done what I said. I only had time to look at the commit message, and not the commit itself 

I can now see that this isn't the case, and that Gamer64 has not followed my suggestion, instead simply re-marking the PR as ready for review with no changes

@Gamer64ytb I am going to re-mark this PR as a draft. To make myself clear this time, before you mark this as ready for review, please make it so that all code which was previously removed in this PR is now conditionally included if a debug build is being produced

**Comment by rtiangha** [comment]
I'm just going to chime in and say that when GPUCode switched everything over to use the Tracy profiler, he also put in a switch in the master CMakeLists.txt that makes it easy to disable during building (`option(ENABLE_PROFILING "Enables integration with the Tracy profiler" ON)`). That can be used as an example on how to do the same with the stock Microprofiler (look at the code changes for hints); I think it can all be done just by modifying the various cmake files.

**Review by BlurrySquire — CHANGES_REQUESTED** [review]
Please update the code so that the micro profiler is not removed but is put behind a cmake config option. Like @rtiangha has said.

I would prefer the micro profilers stay for debugging purposes but are set behind a cmake config. It can then be set to false so that it can be disabled in release builds.

**Comment by ayrudev** [comment]
If you're no longer going to update your pull requests, please close them

**Comment by OpenSauce04** [comment]
I am going to close this PR due to lack of activity and communication despite repeatedly reaching out
Please open a new PR if you decide to implement the requested changes at a later time

**Pull request closed without merging**
