### PR TITLE
Bump MacOS CMake target to MacOS 13

### PR DESCRIPTION
**Pull request by OpenSauce04**

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Unsure why this is failing *specifically* on x86_64. I'm not entirely sure what changing the MacOS target version actually does, so I'll have to do a bit of research on this later. The error isn't particularly helpful.

**Comment by rtiangha** [comment]
I'm not sure _why_ it fails when the OSX version is bumped up, but it's an issue with Zydis that's since been fixed. See https://github.com/zyantific/zydis/issues/350 and https://github.com/zyantific/zydis/issues/474.

So the answer is to update the Zydis dependency used in the dynarmic version that Lime3DS uses. You could also use or fork my master branch; I keep the dependencies somewhat up-to-date:

https://github.com/rtiangha/dynarmic

Or fork PabloMK7's branch and manually update Zydis (since I can't remember if I had to make changes on the Citra side to play nicely with some of the newer dependencies either; it was a while ago).

**Comment by OpenSauce04** [comment]
Seeing as you're already putting in the work, I don't see any reason not to use yours.
I'll update the dependency tomorrow evening and try compiling this PR again.

**Comment by rtiangha** [comment]
I'm testing it now with the Lime3DS codebase. When it's done compiling, I'll post the results. I _think_ it should work with the master branch with no mods on this end; if not, I'll figure out why and how to fix (I can't remember if I ran into issues with Xbyak or fmt conflicts that required a minor cmake change to bump up or set a policy or two).

**Comment by rtiangha** [comment]
Looks like it worked.

https://github.com/rtiangha/Lime3DS/actions/runs/10188175631/job/28183784346

I'll submit a seperate dependency PR without the OSX change since I noticed that SDL also got an update (better gamepad support, from what I can glean from the commit log) so might as well get that one in too.

**Comment by OpenSauce04** [comment]
oop looks like github picked up on the "Close #xxx" keyword 🙃

**Comment by OpenSauce04** [comment]
Successfully tested on my end

**Pull request merged**
