### PR TITLE
android: Implement quick configure for external controllers

### PR DESCRIPTION
**Pull request by newhinton**
This PR implements a fast-button-mapper.

The user can now click the Auto Configuration setting in the gamepad-section, which will open a new dialog.
This dialog will then iterate over the available buttons, where the user can quickly press a button on the gamepad without having to pre-select which button this press should be assigned to.
image

This PR is currently a work in progress.

Todo's:

- [ ] Fix Analog Axis assignment
- [x] Change strings to a consistent namingscheme, also figure out how this should be called
- [ ] Evaluate `MotionBottomSheetDialogFragment` so that we don't have code duplication like now
- [ ] Clicking the Next button seems to not actually skip to the next button the first time you press it, instead duplicating the button into both the current and previous button slots. It must be pressed a second time to actually progress to the next button
- [x] Closing the prompt before reaching the end still applies all previously selected binds. The binds should only be applied if the process is completed
- [ ] Using dpad button binds is redundant if axis binds were detected. The button binds should be skipped over if axis binds are applied successfully

Before continuing with the above todo's, i'd like your opinion on both the implementation and the feature itself.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
I haven't looked at any of the code yet, but on a purely functional basis, I support the inclusion of this feature and think it has a place in the emulator. I have experienced some issues which aren't mentioned in the original message which must be addressed before this is brought out of draft:
- Clicking the Next button seems to not actually skip to the next button the first time you press it, instead duplicating the button into both the current and previous button slots. It must be pressed a second time to actually progress to the next button
- ~~Closing the prompt before reaching the end still applies all previously selected binds. The binds should only be applied if the process is completed~~
- Using dpad button binds is redundant if axis binds were detected. The button binds should be skipped over if axis binds are applied successfully
- ~~Sometimes pressing buttons doesn't actually do anything~~ <-- This was simply the debounce timer being too high

**Comment by OpenSauce04** [comment]
I haven't got enough time right now to look over everything, and my current changes are simply a broad-strokes set of quick and easy things which I picked up during my initial skim read. I will give this a more in-depth review tomorrow, so please wait on that before changing anything else

**Comment by OpenSauce04** [comment]
Code structure seems fine to me. All issues I had with the code itself I have addressed manually.
The issues I mentioned prior still have to be resolved, however.

**Comment by newhinton** [comment]
Great!

What should we do with the bottom-sheet. Should that just stay or should i try to replace it with that dialog to reduce code duplication?

**Comment by OpenSauce04** [comment]
@newhinton Is this still being worked on?

**Comment by newhinton** [comment]
@OpenSauce04 Yes, but not on a high priority. Might take a while.

**Comment by OpenSauce04** [comment]
Rebased for Azahar in #599

**Pull request closed without merging**
