### PR TITLE
strings: Update `contributors_description`

### PR DESCRIPTION
**Pull request by ghost**
The original `contributors_description` string didn't make sense for a couple reasons

- Lime3DS is mostly a solo endeavor. Yes we have a few regular contributors but calling it a Team didn't make sense
- The entire emulator wasn't made by the Lime3DS Team, proper credits to Citra team and their external contributors is given

Updating string is

```
Thanks to the original Citra team, their contributors, and the Lime3DS contributors as well for continuing the work on Citra
```

### CODE REVIEW

**Comment by OpenSauce04** [comment]
You need to only change the English strings, and the other languages will be  handled by Transifex. If you try to contribute translations like this, they will simply be overwritten next time the translations are updated.

**Comment by ghost** [comment]
Oh, right, forgot about translex 

Make sure to fix the french one  saying  yuzu team

**Comment by OpenSauce04** [comment]
Old translations get invalidated when a string is changed, so it'll sort itself out

**Comment by OpenSauce04** [comment]
Addressed in https://github.com/Lime3DS/Lime3DS/commit/0a164af12ef32a71e111f91691495e8e063599f4

**Comment by ghost** [comment]
I guess that works xd

**Pull request closed without merging**
