### PR TITLE
Drop `lime3ds-cli` executable and SDL2 frontend

### PR DESCRIPTION
**Pull request by OpenSauce04**
To my knowledge there is no real use case for including this anymore. You can call the GUI program from the command line to the same effect, and any niche differences are likely not worth the clutter of distributing an entire extra program which continues to confuse less technically inclined users to this day despite them being renamed in an attempt at clarity.

As a consequence of this, the PR also removes all references and use of SDL2, as the CLI executable is the only place where this was ever used.

This PR also renames the `lime3ds-gui` executable to simply `lime3ds` due to the suffix now being redundant.

Additionally, the `dedicated_room` directory has been renamed to `lime_room` to more clearly signify that it contains the code for `lime3ds-room`. This isn't exactly related to the PR subject, but other similar code is being refactored here and this doesn't really warrant its own PR.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
License header warnings will be ignored due to all changes simply being code removal

**Comment by OpenSauce04** [comment]
Testing to ensure that this doesn't inadvertently affect functionality on any platform:
- [x] Linux
- [x] Windows
- [x] MacOS
- [x] Android

**Comment by rtiangha** [comment]
FYI, this breaks gamepad/joystick support on desktop as SDL is also used for the input drivers. Or at least, my wired USB Logitech F310 no longer registers; I don't have a Bluetooth controller so I can't test that.

**Comment by BlurrySquire** [comment]
I am also unable to use my PDP Afterglow Xbox controller. I am also unable to configure the controls (they were already set from testing a previous build).

**Comment by OpenSauce04** [comment]
> FYI, this breaks gamepad/joystick support on desktop as SDL is also used for the input drivers

Damn, sorry I'll fix that now. No idea how I didn't catch that :^)

**Pull request merged**
